#!/bin/bash

# validate_setup.sh - Script to guide the user through the sandbox validation process.

echo "================================================================="
echo "  AI Jail Sandbox Validation Script"
echo "================================================================="
echo "This script guides you through testing the sandbox capabilities"
echo "using the Obsidian Chronology plugin."
echo ""
echo "Prerequisites: You need a running Incus container for this test."
echo "It is recommended to run this script in one terminal (Host)"
echo "and have a second terminal open for the container shell."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 0: Setup & Connection"
echo "-----------------------------------------------------------------"
echo "1. Map the Host Directory:"
echo "   Ensure your project directory is mapped to the container."
echo "   Command (Host):"
echo "     incus config device add <container_name> project disk source=$(pwd) path=/home/dev/project"
echo ""
echo "2. Login to the Container:"
echo "   Command (Host):"
echo "     incus exec <container_name> -- su - dev"
echo "     # OR if SSH is set up:"
echo "     ssh dev@<container_name>.incus"
echo ""
echo "3. Prepare directory:"
echo "   Command (Container):"
echo "     cd /home/dev/project"
echo ""
read -p "Press Enter when you are logged in and ready..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 1: Clone the plugin repo"
echo "-----------------------------------------------------------------"
echo "Run this command inside the container (e.g., in /home/dev/project):"
echo ""
echo "  git clone https://github.com/Canna71/obsidian-chronology plugin-repo"
echo ""
read -p "Press Enter when complete..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 2: Create a dedicated Obsidian vault"
echo "-----------------------------------------------------------------"
echo "Run these commands inside the container to create the vault structure:"
echo ""
echo "  mkdir -p vault/.obsidian/plugins/obsidian-chronology"
echo "  echo '{\"theme\":\"system\"}' > vault/.obsidian/appearance.json"
echo ""
read -p "Press Enter when complete..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 3: Open the test vault on the Host"
echo "-----------------------------------------------------------------"
echo "Action: Open Obsidian on your Host OS."
echo "        Select 'Open folder as vault' and navigate to your shared folder."
echo "        Select the 'vault' directory you just created."
echo ""
read -p "Press Enter when you have the vault open..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 4: Build and Install the Plugin"
echo "-----------------------------------------------------------------"
echo "Run these commands inside the container:"
echo ""
echo "  cd plugin-repo"
echo "  npm install"
echo "  npm run build"
echo "  cp main.js manifest.json styles.css ../vault/.obsidian/plugins/obsidian-chronology/"
echo ""
read -p "Press Enter when complete..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 5: Verify Plugin Loads"
echo "-----------------------------------------------------------------"
echo "Action: In Obsidian (Host):"
echo "  1. Go to Settings -> Community Plugins"
echo "  2. Turn OFF 'Restricted mode'"
echo "  3. Enable 'Chronology'"
echo "  4. Check the Console (Ctrl+Shift+I) for errors."
echo ""
read -p "Press Enter if the plugin loaded successfully..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 6: Modify the Plugin"
echo "-----------------------------------------------------------------"
echo "Run this command to append a log message to the source code:"
echo ""
echo "  sed -i '/async onload() {/a \\t\\tconsole.log(\"HELLO FROM SANDBOX\");' main.ts"
echo ""
echo "Now rebuild and update:"
echo ""
echo "  npm run build"
echo "  cp main.js ../vault/.obsidian/plugins/obsidian-chronology/"
echo ""
read -p "Press Enter when complete..."

echo ""
echo "-----------------------------------------------------------------"
echo "STEP 7: Verify Modification"
echo "-----------------------------------------------------------------"
echo "Action: In Obsidian (Host):"
echo "  1. Reload Obsidian (Ctrl+R)"
echo "  2. Open Console (Ctrl+Shift+I)"
echo "  3. Verify you see 'HELLO FROM SANDBOX'"
echo ""
read -p "Press Enter to finish..."

echo ""
echo "Validation Complete!"
